### ISSUE TITLE
Is there a way to reset the offset of a consumer group?

### ISSUE THREAD

**Issue by rodoufu** [kafka-rust/kafka-rust#197]
Every time an application starts I need to read the last message, so I need to set an offset of `current - 1`.
So I need to set an offset smaller than the current one, how could I do that?

I've tried to use the `commit_offsets` from the `Consumer` with the numbers I want but it does not work.

Something like:
```sh
kafka-consumer-groups --bootstrap-server <kafkahost:port> --group <group_id> --topic <topic_name> --reset-offsets --to-earliest
```

https://gist.github.com/marwei/cd40657c481f94ebe273ecc16601674b

I don't want to use a new consumer group every time the application restarts.

**Comment by johnward** [comment]
The offset should be commited once the record has been processed by the consumer so the expected behaviour is that  Kafka to give you the next unprocessed record.

What is the reason for getting the last record processed by the consumer?

I'm really interested to hear about your use case.

Thanks,

John

**Comment by dead10ck** [comment]
Is seems like what you want is for the high water mark to always be one behind the must recent message so that if the service restarts, it starts at the must recent message again, even if it's been processed before. It seems like the must appropriate thing to do to achieve this would be to always consume one message behind the latest in the topic. So you could keep track of the second to last message in each message set and consume that with [`consume_message`](https://docs.rs/kafka/0.8.0/kafka/consumer/struct.Consumer.html#method.consume_message) at the end of the message set loop.

**Comment by rodoufu** [comment]
> Is seems like what you want is for the high water mark to always be one behind the must recent message so that if the service restarts, it starts at the must recent message again, even if it's been processed before. It seems like the most appropriate thing to do to achieve this would be to always consume one message behind the latest in the topic. So you could keep track of the second to last message in each message set and consume that with [`consume_message`](https://docs.rs/kafka/0.8.0/kafka/consumer/struct.Consumer.html#method.consume_message) at the end of the message set loop.

I cannot delay processing messages, but I can delay commiting it.

**Comment by dead10ck** [comment]
That's right. Committing is separate; a consumer will always read to the end, no matter what progress you commit on your consumer group. So if you always commit one behind, that should hit your use case.

**Comment by johnward** [comment]
@rodoufu, please let me know if dead10ck's solution worked for you. Thanks.

**Comment by rodoufu** [comment]
> @rodoufu, please let me know if dead10ck's solution worked for you. Thanks.

Yes, it did.
